c_all = "All object models"
c_alpha_channels_and_non_collidable = "Alpha channels and non-collidable"
c_nighttime_objects = "Nighttime objects"
c_beach_and_sea = "Beach and sea"
c_buildings = "Buildings"
c_factories_and_warehouses = "Factories and warehouses"
c_stores_and_shops = "Stores and shops"
c_graveyard = "Graveyard"
c_houses_and_apartments = "Houses and apartments"
c_offices_and_skyscrapers = "Offices and skyscrapers"
c_other_buildings = "Other buildings"
c_restaurants_and_hotels = "Restaurants and hotels"
c_sports_and_stadium_objects = "Sports and stadium objects"
c_bars_clubs_and_casinos = "Bars, clubs, and casinos"
c_car_parts = "Car parts"
c_weapon_models = "Weapon models"
c_industrial = "Industrial"
c_general_industrial = "General"
c_construction_industrial = "Construction"
c_cranes = "Cranes"
c_crates_drums_and_racks = "Crates, drums and racks"
c_interior_objects = "Interior objects"
c_bar_items = "Bar items"
c_shop_items = "Shop items"
c_household_items = "Household items"
c_furniture = "Furniture"
c_doors_and_windows = "Doors and windows"
c_clothes = "Clothes"
c_tables_and_chairs = "Tables and chairs"
c_casino_items = "Casino items"
c_more_interiors = "More interiors"
c_land_masses = "Land masses"
c_concrete_and_rock = "Concrete and rock"
c_grass_and_dirt = "Grass and dirt"
c_miscellaneous = "Miscellaneous"
c_street_and_road_items = "Street and road items"
c_food_and_drinks = "Food and drinks"
c_special = "Special"
c_military = "Military"
c_pickups_and_icons = "Pickups and icons"
c_ladders_stairs_and_scaffolding = "Ladders, stairs and scaffolding"
c_trash = "Trash"
c_lights = "Lights"
c_map_markers = "Map markers"
c_nature = "Nature"
c_rocks = "Rocks"
c_trees = "Trees"
c_plants = "Plants"
c_structures = "Structures"
c_airport_and_aircraft_objects = "Airport and aircraft objects"
c_car_parks = "Car parks"
c_farm_objects = "Farm objects"
c_fences_walls_gates_and_barriers = "Fences, walls, gates and barriers"
c_garages_and_petrol_stations = "Garages and petrol stations"
c_ramps = "Ramps"
c_signs_billboards_and_statues = "Signs, billboards and statues"
c_transportation = "Transportation"
c_railroads = "Railroads"
c_roads_bridges_and_tunnels = "Roads, bridges and tunnels"
c_wires_and_cables = "Wires and cables"
c_construction = "Construction"
c_stunt_tubes = "Tubes and stunt constructions"
c_walls = "Walls"
c_modular_island = "Modular island"
c_samp_particles = "SA-MP particles"
