o_211_a_handheld_device = "Карманные устройства"
o_67_accessories = "Аксессуары"
o_195_air_conditioning = "Кондиционеры"
o_178_airplanes = "Самолеты"
o_416_alcohol = "Алкоголь"
o_156_angara = "Ангары"
o_140_animals = "Животные"
o_175_antenna = "Антенны"
o_133_apartments = "Квартиры"
o_55_area_51 = "Зона 51"
o_36_army = "Армия"
o_198_atms = "Банкоматы"
o_176_aviation = "Авиация"
o_210_badges_and_chevrons = "Значки и шевроны"
o_51_bag = "Мешок"
o_383_bags = "Сумки"
o_419_balconies = "Балконы"
o_408_balloons = "Воздушные шары"
o_43_bar = "Бар"
o_128_barrels = "Бочки"
o_102_barriers = "Шлагбаумы"
o_429_basket_purchasing = "Корзины покупательские"
o_14_bathroom = "Ванная"
o_125_bed = "Кровать"
o_381_benches = "Лавочки"
o_180_big_boards = "Биг-борды"
o_3_billiards = "Бильярд"
o_405_black = "Черный"
o_396_blocks = "Блоки"
o_159_blood = "Кровь"
o_202_blue = "Синий"
o_116_bottle = "Бутылки"
o_126_boxes = "Ящики"
o_121_bridges = "Мосты"
o_11_building = "Здания"
o_174_bumpers = "Бамперы"
o_183_burger_shot = "Burger Shot"
o_127_cabinets = "Шкафы"
o_118_cafes_and_restaurants = "Кафе и рестораны"
o_37_camouflage = "Камуфляж"
o_16_cardboard_boxes = "Картонные коробки"
o_149_carpets = "Ковры"
o_91_casino = "Казино"
o_399_cat = "КПП"
o_389_cemetery = "Кладбище"
o_143_chairs = "Стулья"
o_29_chicken = "Курица"
o_90_chips = "Фишки"
o_407_christmas_new_year = "Новый год, рождество"
o_168_cigarette = "Сигареты"
o_34_clothing = "Одежда"
o_28_cluckin_bell = "Cluckin bell"
o_384_coffee = "Кофе"
o_69_construction = "Строительство"
o_25_containers = "Контейнеры"
o_229_corpses = "Трупы"
o_70_cranes = "Краны"
o_47_crossroads = "Перекрестки"
o_193_cuisine_ = "Кухни"
o_177_destroyed = "Разрушенное"
o_107_disco = "Дискотека"
o_72_door = "Двери"
o_425_drinks = "Напитки"
o_7_drugs = "Наркотики"
o_86_dunes = "Дюны"
o_231_easter = "Пасха"
o_230_eggs = "Яйца"
o_50_electrician = "Электрика"
o_61_electronics = "Электроника"
o_370_explosives = "Взрывчатка"
o_44_exterior = "Экстерьер"
o_205_falloimitatory = "Фалоимитаторы"
o_218_farm = "Ферма"
o_39_fences_and_fencing = "Заборы и ограждения"
o_217_ferris_wheel = "Чертово колесо"
o_104_field = "Поле"
o_199_fire_extinguishers = "Огнетушители"
o_166_flags = "Флаги"
o_120_flashlight = "Фонарик"
o_58_floors = "Этажи"
o_132_flowers = "Цветы"
o_45_food = "Еда"
o_112_for_trade = "Для торговли"
o_173_fridge = "Холодильник"
o_413_fuel = "Топливо"
o_216_fueling_and_bus_station = "Заправки и автостанции"
o_155_furniture = "Мебель"
o_10_garage = "Гараж"
o_237_garage_equipment = "Гаражное оборудование"
o_27_garbage = "Мусор"
o_108_gardens = "Сады"
o_109_gardens = "Огороды"
o_54_gate = "Ворота"
o_380_generators = "Генераторы"
o_66_glasses = "Очки"
o_200_glasses = "Стаканы"
o_196_golf = "Гольф"
o_18_graffiti = "Надписи на стенах"
o_19_graffiti = "Граффити"
o_87_grass = "Трава"
o_160_green = "Зеленый"
o_220_grey = "Серый"
o_379_grill = "Гриль"
o_191_grille = "Решетка"
o_99_half_pipe = "Половины труб"
o_181_halloween = "Хэллоуин"
o_71_hatches = "Люки"
o_38_hats = "Головные уборы"
o_371_hay = "Сено"
o_79_head = "Голова"
o_214_headphones = "Наушники"
o_68_hedge = "Живая изгородь"
o_187_helicopters = "Вертолеты"
o_209_helipad = "Вертолетные площадки"
o_35_helmet = "Шлем"
o_122_high_rise_building = "Многоэтажные здания"
o_33_hills = "Холмы"
o_422_hospital = "Больница"
o_114_hotels_and_hotels = "Отели и гостинницы"
o_426_household_chemicals = "Бытовая химия"
o_235_in_a_pot = "В горшке"
o_48_industry = "Промышленность"
o_232_information_boards = "Информационное табло"
o_59_interiors_and_interior_details = "Интерьер и детали интерьера"
o_134_items_economy = "Предметы хозяйства"
o_376_jetpack = "Jetpack"
o_141_jumps = "Трамплины"
o_92_keys = "Клавиши"
o_150_kitchen_appliances = "Кухонные приборы"
o_411_kitchen_furniture = "Кухонная мебель"
o_221_lasers = "Лазеры"
o_391_liberty_city = "Либерти Сити"
o_139_light = "Свет"
o_96_light_windows = "Свет окон"
o_186_lighting = "Освещение"
o_135_lights = "Фонари"
o_428_logos = "Логотипы"
o_56_machine_parts = "Детали машин"
o_382_magazines = "Журналы"
o_430_magnet = "Магнит"
o_392_mailboxes = "Почтовые ящики"
o_233_map = "Карты"
o_157_map_markers = "Маркеры для карты"
o_170_marine_life = "Морские обитатели"
o_373_markup = "Разметки"
o_369_mask = "Маски"
o_52_meat = "Мясо"
o_184_medicine = "Медицина"
o_40_mesh = "Сетка"
o_74_metal = "Металл"
o_131_military_equipment = "Военный инвентарь"
o_161_mobile_phones = "Мобильные телефоны"
o_228_moorings = "Причалы"
o_194_mufflers = "Глушители"
o_146_musical_instrument = "Музыкальная аппаратура"
o_73_needles = "Хвоя"
o_88_neon_light = "Неоновый свет"
o_62_office_furniture = "Офисная мебель"
o_26_on_the_wall = "Настенное"
o_24_one_floor = "Один этаж"
o_185_orange = "Оранжевый"
o_164_overpass = "Эстакады"
o_6_package = "Пакет"
o_414_palm_trees = "Пальмы"
o_101_parking = "Парковки"
o_406_particle_particles_ = "Партиклы (частицы)"
o_238_parts_of_the_tree = "Части дерева"
o_397_pay_n_spray = "Pay-n-spray"
o_182_pickups_pickups_ = "Пикапы (pickups)"
o_129_picture = "Картины"
o_225_pink = "Розовый"
o_21_pipe = "Трубы"
o_197_pizza = "Пицца"
o_32_plants = "Растения"
o_393_playground = "Спортивные площадки"
o_15_plumbing = "Сантехника"
o_427_poker = "Покер"
o_192_police = "Полиция"
o_158_posters_and_signage = "Постеры и вывески"
o_136_posts = "Столбы"
o_418_power_supplies = "Источники питания"
o_385_printers = "Принтеры"
o_412_prison = "Тюрьма"
o_400_protection = "Охрана"
o_188_protection = "Защита"
o_17_purple = "Фиолетовый"
o_142_quarry = "Карьер"
o_76_rack = "Стеллаж"
o_65_rails = "Рельсы"
o_64_railway = "Железная дорога"
o_130_rainbow = "Радуга"
o_5_red = "Красный"
o_13_residential_house = "Жилой дом"
o_145_rifle = "Винтовки"
o_9_road = "Дорога"
o_82_road_block_posts = "Дорожные блок-посты"
o_215_road_bumpers = "Дорожные бортики"
o_98_road_signs = "Дорожные знаки"
o_417_roof = "Крыша"
o_4_round = "Круглое"
o_103_rusty = "Ржавый"
o_377_safes = "Сейфы"
o_189_satellite_dish = "Спутниковая тарелка"
o_208_service = "Сервис"
o_151_ships = "Корабли"
o_117_shops = "Магазины"
o_137_shore = "Берег"
o_372_signs = "Знаки"
o_179_slot_machines = "Игровые автоматы"
o_409_smooth_plane = "Ровные плоскости"
o_390_snow = "Снег"
o_213_sofas_ = "Диваны"
o_163_spoiler = "Спойлера"
o_410_sport = "Спорт"
o_154_sports_equipment = "Спортивный инвентарь"
o_153_sports_facilities = "Спортивные заведения"
o_212_sprunk = "Sprunk"
o_95_stairs = "Лестницы"
o_89_stand = "Стойки"
o_388_statues = "Статуи"
o_84_stone = "Камень"
o_394_stripe = "Нашивки"
o_395_sunbeds = "Лежаки"
o_172_supermarket = "Супермаркет"
o_234_support = "Опоры"
o_60_tables = "Столы"
o_424_tanks = "Резервуары"
o_415_tara = "Тара"
o_77_target = "Мишени"
o_171_the_airports = "Аеропорты"
o_162_the_ball = "Мяч"
o_387_the_beach = "Пляж"
o_53_the_bushes = "Кусты"
o_78_the_church = "Церковь"
o_23_the_landscape = "Ландшафт"
o_8_the_shadow_of_the_landscape = "Тень от ландшафта"
o_20_the_stunt = "Стант"
o_167_the_traffic_light = "Светофор"
o_204_three_floors = "Три этажа"
o_421_toilet = "Туалет"
o_378_towels = "Полотенца"
o_148_tower = "Вышки"
o_206_toys = "Игрушки"
o_152_trailer = "Трейлер"
o_111_trailers = "Прицепы"
o_123_trash_can = "Мусорный бак"
o_203_trays = "Подносы"
o_31_tree = "Дерево"
o_207_truck = "Тележка"
o_57_tuning = "Тюнинг"
o_93_tunnels = "Туннели"
o_374_tunnels = "Тоннели"
o_63_tvs = "Телевизоры"
o_12_two_floors = "Два этажа"
o_119_umbrellas = "Зонтики"
o_94_underground_structures = "Подземные сооружения"
o_81_unknown_objects = "Неизвестные объекты"
o_224_useful = "Полезное"
o_219_utensils_for_the_kitchen = "Посуда для кухни"
o_423_vegetables = "Овощи"
o_83_vending_machines = "Автоматы с едой"
o_97_wall = "Стены"
o_75_warehouses = "Склады"
o_236_watch = "Часы"
o_386_water = "Вода"
o_144_weapons = "Оружие"
o_85_wheels = "Колеса"
o_115_white = "Белый"
o_113_wigs = "Парики"
o_226_windows = "Окна"
o_49_wire = "Провода"
o_420_wood = "Дрова"
o_22_wooden = "Деревянное"
o_147_wrist_watch = "Наручные часы"
o_110_yards = "Дворы"
o_80_yellow = "Желтый"
o_347_0_3_7_rc3_misc_items = "Разное из 0.3.7 RC3"
o_339_0_3_7_rc3_stuff = "Хлам из 0.3.7 RC3"
o_363_0_3_7_rc4_extracted_items = "Извлеченные в 0.3.7 RC4"
o_366_0_3_7_rc4_misc_items = "Разное из 0.3.7 RC4"
o_303_360_degree_ramps = "Трамплины на 360 градусов"
o_300_3d_fish_bream_ = "3Д рыба (лещ)"
o_357_a51_replacement_land_bit = "Территория зоны 51"
o_361_ambulance_lights = "Огни скорой помощи"
o_331_animated_waterfalls = "Анимированные водопады"
o_349_area_51_69_buildings = "Здания зоны 51 (69)"
o_402_area_boundaries = "Границы зон"
o_274_atm_fixed = "Исправный банкомат"
o_325_balaclava = "Балаклава"
o_246_base_sections = "Базовые секции"
o_302_burning_logs = "Горящие дрова"
o_323_caligula_s_casino_vault_door = "Дверь хранилища казино Калигула"
o_334_cargobob_platform = "Платформа КаргоБоба"
o_401_checkpoints_from_0_3_7_rc3 = "Чекпоинты из 0.3.7 RC3"
o_294_coloured_enter_exit_markers = "Цветные маркеры входа / выхода"
o_312_crushed_car_cube = "Сжатый в куб автомобиль"
o_317_cubes = "Кубы"
o_340_dillimore_gas_station = "Заправка Dillimore"
o_248_dm_cages = "Клетки для ДМ"
o_247_elevator_from_vc = "Лифт из VC"
o_305_empty_shop_shelf = "Пустая полка из магазина"
o_298_extracted_from_cutscene_img = "Извлеченное из кат-сцен"
o_277_extracted_from_skins = "Извлеченные из скинов"
o_329_extracted_items = "Извлеченные вещи"
o_319_fire_wood_log = "Полено"
o_351_from_cutscene_img = "Из кат-сцен"
o_279_fruit = "Фрукты"
o_304_fruit_crates = "Ящики с фруктами"
o_341_gtasa_skateboard = "Скейтбоард GTASA"
o_367_handcuffs = "Наручники"
o_365_hold_all_carry_bag_ = "Большая сумка"
o_240_holding_objects = "Объекты, которые можно держать"
o_310_join_medium_and_small_tubes = "Соединение средних и малых труб"
o_308_join_normal_and_medium_tubes = "Соединение нормальных и средних труб"
o_342_kylie_s_arn = "Сарай Кайла"
o_245_land_masses = "Массивы суши"
o_293_landmine = "Мина"
o_346_laptop_old_style_ = "Ноутбук (старый стиль)"
o_314_lcd_tvs = "LCD телевизоры"
o_333_leg_of_ham = "Окорок"
o_280_loaf_of_bread = "Буханка хлеба"
o_289_ls_apartments = "Квартиры ЛС"
o_322_ls_apartments_car_park = "Паркинг квартир ЛС"
o_290_ls_beach_side = "Берег ЛС"
o_324_ls_beach_side_car_park = "Паркинг берега ЛС"
o_320_ls_prison_walls_and_gates = "Стены и ворота тюрьмы ЛС"
o_362_magnetic_crane = "Магнитный кран"
o_364_marco_s_bistro = "Бистро Марко"
o_282_marco_s_bistro_kitchen = "Кухня Бистро Марко"
o_343_marco_s_steak_cooked = "Стейк Марко"
o_350_metal_gate_and_big_fence = "Металлические ворота и большой забор"
o_332_metal_panels = "Металлические панели"
o_255_modular_bridge_sections = "Части мостов"
o_276_modular_island = "Модульный остров"
o_335_modular_island_house = "Дом модульного острова"
o_316_modular_island_road_corner = "Угол дороги на модульном острове"
o_352_modular_kitchen = "Модульная кухня"
o_299_modular_road_banked_corners = "Заокругленные углы частей дорог"
o_254_modular_road_sections = "Части дороги"
o_359_modular_rope_bridge = "Модульный подвесной мост"
o_360_more_road_signs = "Больше дорожных знаков"
o_258_more_stuff = "Разное"
o_297_new_police_light_bar = "Новые полицейские мигалки"
o_336_non_breakable_mail_box = "Неразрушимый почтовый ящик"
o_337_non_breakable_mesh_fences_and_gate = "Неразрушимые сетчатые заборы и ворота"
o_318_normal_sized_keycard = "Карточка пропуска нормального размера"
o_330_objects_that_use_particle_txd = "Объекты, которые используют particle.TXD"
o_328_padlock = "Замок"
o_250_parkour = "Паркур"
o_281_pepperoni_pizza = "Пицца пепперони"
o_283_plastic_tray = "Пластмассовый лоток"
o_313_police_and_fbi_stuff = "Вещи полиции и ФБР"
o_321_police_visor_strobe = "Строб визора полиции"
o_272_property_icons = "Значки недвижимости"
o_249_racing = "Гоночное"
o_355_redsands_west_casino = "Казино Redsands West"
o_285_rubbish_skip = "Мусорный контейнер"
o_2_sa_mp = "SA-MP"
o_271_sa_mp_0_3_7_rc1 = "САМП 0.3.7 RC1"
o_315_sa_mp_0_3_7_rc2 = "САМП 0.3.7 RC2"
o_338_sa_mp_0_3_7_rc3 = "САМП 0.3.7 RC3"
o_356_sa_mp_0_3_7_rc4 = "САМП 0.3.7 RC4"
o_239_sa_mp_0_3c_rc1 = "САМП 0.3c RC1"
o_259_sa_mp_0_3c_rc2_and_rc3 = "САМП 0.3c RC2 и RC3"
o_260_sa_mp_0_3c_rc4 = "САМП 0.3c RC4"
o_261_sa_mp_0_3c_rc5 = "САМП 0.3c RC5"
o_264_sa_mp_0_3d = "САМП 0.3d"
o_262_sa_mp_0_3d_rc3_3 = "САМП 0.3d RC3-3"
o_263_sa_mp_0_3d_rc7 = "САМП 0.3d RC7"
o_265_sa_mp_0_3e_rc1 = "САМП 0.3e RC1"
o_266_sa_mp_0_3e_rc3 = "САМП 0.3e RC3"
o_267_sa_mp_0_3e_rc4 = "САМП 0.3e RC4"
o_268_sa_mp_0_3e_rc6 = "САМП 0.3e RC6"
o_269_sa_mp_0_3e_rc7 = "САМП 0.3e RC7"
o_270_sa_mp_0_3x_rc2_4 = "САМП 0.3x RC2-4"
o_307_sa_mp_half_tube_objects = "Половины труб SA-MP"
o_275_sa_mp_halloween_stuff = "Хэллоуин из SA-MP"
o_358_sa_mp_hills = "Холмы SA-MP"
o_241_sa_mp_lights = "Свет SA-MP"
o_404_sa_mp_particle_effects = "Эффекты и частицы из SA-MP"
o_253_sa_mp_ramps = "Трамплины SA-MP"
o_354_sa_mp_road_signs = "Дорожные знаки SA-MP"
o_242_sa_mp_spray_tags = "Граффити SA-MP"
o_244_sa_mp_logos = "Логотипы SA-MP"
o_296_safe_with_seperate_door = "Сейф с отдельной дверью"
o_291_sf_building = "Дом из СФ"
o_288_sf_zombotech_building_and_lab = "Здание СФ ZomboTech и лаборатория"
o_287_shop_basket = "Корзинка из универмага"
o_251_sky_diving_platforms = "Платформы для скай дайвинга"
o_301_sledge_hammer = "Кувалда"
o_344_slice_of_bread = "Кусок хлеба"
o_292_snow_plow = "Ковш для снега"
o_257_spheres = "Сферы"
o_295_stage_and_music_equipment = "Сцена и музыкальная аппаратура"
o_326_static_door = "Статичная дверь"
o_278_supermarket_items = "Предметы супермаркетов"
o_327_tow_truck_lights = "Огни эвакуатора"
o_256_tubes_and_funnels = "Трубы и воронки"
o_309_tubes_medium_size = "Трубы среднего размера"
o_311_tubes_small_size = "Трубы малого размера"
o_252_tunnel_sections = "Части туннелей"
o_403_water_plane = "Плоскости из воды"
o_345_water_slide_sections = "Части водных горок"
o_273_wedding_cake = "Свадебный торт"
o_306_wooden_fence_section = "Часть деревянного забора"
o_284_wooden_foot_bridge = "Деревянный пешеходный мост"
o_286_woozie_s_apartment = "Квартира Вузи"
