import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
export default {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        title: 'Getting started',
        slug: '/category/getting-started',
        keywords: ['getting started'],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting_started",
        }
      ],
    },
  ],
};
