import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export default {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        title: 'Getting started',
        slug: '/category/getting-started',
        keywords: ['getting started'],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting_started",
        }
      ],
    },
  ],
} satisfies SidebarsConfig;
