[window.padding]
    value = [6, 6]

[window.rounding]
    value = 1.5

[frame.padding]
    value = [5, 5]

[frame.rounding]
    value = 4.0

[item.spacing]
    value = [12, 4]

[scrollbar.size]
    value = 15.0

[scrollbar.rounding]
    value = 9.0

[grab.min.size]
    value = 5.0

[grab.rounding]
    value = 3.0

[button.text.align]
    value = [0.5, 0.35]

[frame.border.size]
    value = 0.0

# Colors

[text]
    value = [0.80, 0.80, 0.83, 1.00]

    [text.disabled]
        value = [0.24, 0.23, 0.29, 1.00]

[window.bg]
    value = [0.06, 0.05, 0.07, 1.00]

[child.bg]
    value = [0.07, 0.07, 0.09, 1.00]

[popup.bg]
    value = [0.07, 0.07, 0.09, 1.00]

[border]
    value = [0.80, 0.80, 0.83, 0.88]

    [border.shadow]
        value = [0.92, 0.91, 0.88, 0.00]

[frame.bg]
    value = [0.10, 0.09, 0.12, 1.00]

    [frame.bg.hovered]
        value = [0.24, 0.23, 0.29, 1.00]

    [frame.bg.active]
        value = [0.56, 0.56, 0.58, 1.00]

[title.bg]
    value = [0.10, 0.09, 0.12, 1.00]

    [title.bg.active]
        value = [0.07, 0.07, 0.09, 1.00]

    [title.bg.collapsed]
        value = [1.00, 0.98, 0.95, 0.75]

[menu.bar.bg]
    value = [0.10, 0.09, 0.12, 1.00]

[scrollbar.bg]
    value = [0.10, 0.09, 0.12, 1.00]

[scrollbar.grab]
    value = [0.80, 0.80, 0.83, 0.31]

    [scrollbar.grab.hovered]
        value = [0.56, 0.56, 0.58, 1.00]

    [scrollbar.grab.active]
        value = [0.06, 0.05, 0.07, 1.00]

[check.mark]
    value = [0.80, 0.80, 0.83, 0.31]

[slider.grab]
    value = [0.80, 0.80, 0.83, 0.31]

    [slider.grab.active]
        value = [0.06, 0.05, 0.07, 1.00]

[button]
    value = [0.10, 0.09, 0.12, 1.00]

    [button.hovered]
        value = [0.24, 0.23, 0.29, 1.00]

    [button.active]
        value = [0.56, 0.56, 0.58, 1.00]

[header]
    value = [0.10, 0.09, 0.12, 1.00]

    [header.hovered]
        value = [0.56, 0.56, 0.58, 1.00]

    [header.active]
        value = [0.06, 0.05, 0.07, 1.00]

[separator]
    value = [0.07, 0.07, 0.09, 1.00]

    [separator.hovered]
        value = [0.24, 0.23, 0.29, 1.00]

    [separator.active]
        value = [0.56, 0.56, 0.58, 1.00]

[resize.grip]
    value = [0.00, 0.00, 0.00, 0.00]

    [resize.grip.hovered]
        value = [0.56, 0.56, 0.58, 1.00]

    [resize.grip.active]
        value = [0.06, 0.05, 0.07, 1.00]

[tab]
    value = [0.07, 0.07, 0.09, 1.00]

    [tab.hovered]
        value = [0.24, 0.23, 0.29, 1.00]

    [tab.active]
        value = [0.56, 0.56, 0.58, 1.00]

    [tab.unfocused]
        value = [0.26, 0.59, 0.98, 0.31]

        [tab.unfocused.active]
            value = [0.26, 0.59, 0.98, 1.00]

[plot.lines]
    value = [0.40, 0.39, 0.38, 0.63]

    [plot.lines.hovered]
        value = [0.25, 1.00, 0.00, 1.00]

[plot.histogram]
    value = [0.40, 0.39, 0.38, 0.63]

    [plot.histogram.hovered]
        value = [0.25, 1.00, 0.00, 1.00]