camera = "Camera"
player = "Player"
math = "Math"
char = "Char"
car = "Car"
text = "Text"
clock = "Clock"
mission = "Mission"
pad = "Pad"
object = "Object"
car_generator = "Car Generator"
hud = "Hud"
blip = "Blip"
restart = "Restart"
fx = "Fx"
sound = "Sound"
weather = "Weather"
path = "Path"
world = "World"
game = "Game"
kill_frenzy = "Kill Frenzy"
pickup = "Pickup"
garage = "Garage"
gang = "Gang"
streaming = "Streaming"
cutscene = "Cutscene"
script_fire = "Script Fire"
boat = "Boat"
zone = "Zone"
stat = "Stat"
txd = "Txd"
audio = "Audio"
sphere = "Sphere"
stuck_car_check = "Stuck Car Check"
credits = "Credits"
rc = "Rc"
heli = "Heli"
plane = "Plane"
task = "Task"
card_decks = "Card Decks"
debugger = "Debugger"
decision_maker_char = "Decision Maker Char"
sequence = "Sequence"
attractor = "Attractor"
group = "Group"
particle = "Particle"
decision_maker = "Decision Maker"
decision_maker_group = "Decision Maker Group"
searchlight = "Searchlight"
checkpoint = "Checkpoint"
train = "Train"
conversation = "Conversation"
shopping = "Shopping"
weapon = "Weapon"
crane = "Crane"
trailer = "Trailer"
streamed_script = "Streamed Script"
menu = "Menu"
skip = "Skip"
menu_grid = "Menu Grid"
other = "Other"
user3_d_marker = "User3 D Marker"
mouse = "Mouse"
memory = "Memory"
fs = "Fs"
file = "File"
dynamic_library = "Dynamic Library"
audio_stream = "Audio Stream"
audio_stream3_d = "Audio Stream3 D"
find_file = "Find File"
ini_file = "Ini File"
