---@class LDNodeEditorNode
---@field id integer
---@field nodeType string
---@field inputs LDNodeEditorPin[]
---@field outputs LDNodeEditorPin[]
---@field position_x number
---@field position_y number