#include "OpcodesLuaWrapper.h"

//This code is generating, it cannot be changed.
extern void KeywordsOpcodesLuaWrapper(sol::state& state);
extern void CameraOpcodesLuaWrapper(sol::state& state);
extern void PlayerOpcodesLuaWrapper(sol::state& state);
extern void MathOpcodesLuaWrapper(sol::state& state);
extern void CharOpcodesLuaWrapper(sol::state& state);
extern void CarOpcodesLuaWrapper(sol::state& state);
extern void TextOpcodesLuaWrapper(sol::state& state);
extern void ClockOpcodesLuaWrapper(sol::state& state);
extern void MissionOpcodesLuaWrapper(sol::state& state);
extern void PadOpcodesLuaWrapper(sol::state& state);
extern void ObjectOpcodesLuaWrapper(sol::state& state);
extern void CarGeneratorOpcodesLuaWrapper(sol::state& state);
extern void HudOpcodesLuaWrapper(sol::state& state);
extern void BlipOpcodesLuaWrapper(sol::state& state);
extern void RestartOpcodesLuaWrapper(sol::state& state);
extern void FxOpcodesLuaWrapper(sol::state& state);
extern void SoundOpcodesLuaWrapper(sol::state& state);
extern void WeatherOpcodesLuaWrapper(sol::state& state);
extern void PathOpcodesLuaWrapper(sol::state& state);
extern void WorldOpcodesLuaWrapper(sol::state& state);
extern void GameOpcodesLuaWrapper(sol::state& state);
extern void KillFrenzyOpcodesLuaWrapper(sol::state& state);
extern void PickupOpcodesLuaWrapper(sol::state& state);
extern void GarageOpcodesLuaWrapper(sol::state& state);
extern void GangOpcodesLuaWrapper(sol::state& state);
extern void StreamingOpcodesLuaWrapper(sol::state& state);
extern void CutsceneOpcodesLuaWrapper(sol::state& state);
extern void ScriptFireOpcodesLuaWrapper(sol::state& state);
extern void BoatOpcodesLuaWrapper(sol::state& state);
extern void ZoneOpcodesLuaWrapper(sol::state& state);
extern void StatOpcodesLuaWrapper(sol::state& state);
extern void TxdOpcodesLuaWrapper(sol::state& state);
extern void AudioOpcodesLuaWrapper(sol::state& state);
extern void SphereOpcodesLuaWrapper(sol::state& state);
extern void StuckCarCheckOpcodesLuaWrapper(sol::state& state);
extern void CreditsOpcodesLuaWrapper(sol::state& state);
extern void RcOpcodesLuaWrapper(sol::state& state);
extern void HeliOpcodesLuaWrapper(sol::state& state);
extern void PlaneOpcodesLuaWrapper(sol::state& state);
extern void TaskOpcodesLuaWrapper(sol::state& state);
extern void CardDecksOpcodesLuaWrapper(sol::state& state);
extern void DebuggerOpcodesLuaWrapper(sol::state& state);
extern void DecisionMakerCharOpcodesLuaWrapper(sol::state& state);
extern void SequenceOpcodesLuaWrapper(sol::state& state);
extern void AttractorOpcodesLuaWrapper(sol::state& state);
extern void GroupOpcodesLuaWrapper(sol::state& state);
extern void ParticleOpcodesLuaWrapper(sol::state& state);
extern void DecisionMakerOpcodesLuaWrapper(sol::state& state);
extern void DecisionMakerGroupOpcodesLuaWrapper(sol::state& state);
extern void SearchlightOpcodesLuaWrapper(sol::state& state);
extern void CheckpointOpcodesLuaWrapper(sol::state& state);
extern void TrainOpcodesLuaWrapper(sol::state& state);
extern void ConversationOpcodesLuaWrapper(sol::state& state);
extern void ShoppingOpcodesLuaWrapper(sol::state& state);
extern void WeaponOpcodesLuaWrapper(sol::state& state);
extern void CraneOpcodesLuaWrapper(sol::state& state);
extern void TrailerOpcodesLuaWrapper(sol::state& state);
extern void StreamedScriptOpcodesLuaWrapper(sol::state& state);
extern void MenuOpcodesLuaWrapper(sol::state& state);
extern void SkipOpcodesLuaWrapper(sol::state& state);
extern void MenuGridOpcodesLuaWrapper(sol::state& state);
extern void OtherOpcodesLuaWrapper(sol::state& state);
extern void User3DMarkerOpcodesLuaWrapper(sol::state& state);
extern void MouseOpcodesLuaWrapper(sol::state& state);
extern void MemoryOpcodesLuaWrapper(sol::state& state);
extern void FsOpcodesLuaWrapper(sol::state& state);
extern void FileOpcodesLuaWrapper(sol::state& state);
extern void DynamicLibraryOpcodesLuaWrapper(sol::state& state);
extern void AudioStreamOpcodesLuaWrapper(sol::state& state);
extern void AudioStream3DOpcodesLuaWrapper(sol::state& state);
extern void FindFileOpcodesLuaWrapper(sol::state& state);
extern void EntityOpcodesLuaWrapper(sol::state& state);
extern void CleoBlipOpcodesLuaWrapper(sol::state& state);
extern void ColPointOpcodesLuaWrapper(sol::state& state);
extern void ClipboardOpcodesLuaWrapper(sol::state& state);
extern void ImGuiOpcodesLuaWrapper(sol::state& state);
extern void IniFileOpcodesLuaWrapper(sol::state& state);

void OpcodesLuaWrapper::wrap(sol::state& state) {
	KeywordsOpcodesLuaWrapper(state);
	CameraOpcodesLuaWrapper(state);
	PlayerOpcodesLuaWrapper(state);
	MathOpcodesLuaWrapper(state);
	CharOpcodesLuaWrapper(state);
	CarOpcodesLuaWrapper(state);
	TextOpcodesLuaWrapper(state);
	ClockOpcodesLuaWrapper(state);
	MissionOpcodesLuaWrapper(state);
	PadOpcodesLuaWrapper(state);
	ObjectOpcodesLuaWrapper(state);
	CarGeneratorOpcodesLuaWrapper(state);
	HudOpcodesLuaWrapper(state);
	BlipOpcodesLuaWrapper(state);
	RestartOpcodesLuaWrapper(state);
	FxOpcodesLuaWrapper(state);
	SoundOpcodesLuaWrapper(state);
	WeatherOpcodesLuaWrapper(state);
	PathOpcodesLuaWrapper(state);
	WorldOpcodesLuaWrapper(state);
	GameOpcodesLuaWrapper(state);
	KillFrenzyOpcodesLuaWrapper(state);
	PickupOpcodesLuaWrapper(state);
	GarageOpcodesLuaWrapper(state);
	GangOpcodesLuaWrapper(state);
	StreamingOpcodesLuaWrapper(state);
	CutsceneOpcodesLuaWrapper(state);
	ScriptFireOpcodesLuaWrapper(state);
	BoatOpcodesLuaWrapper(state);
	ZoneOpcodesLuaWrapper(state);
	StatOpcodesLuaWrapper(state);
	TxdOpcodesLuaWrapper(state);
	AudioOpcodesLuaWrapper(state);
	SphereOpcodesLuaWrapper(state);
	StuckCarCheckOpcodesLuaWrapper(state);
	CreditsOpcodesLuaWrapper(state);
	RcOpcodesLuaWrapper(state);
	HeliOpcodesLuaWrapper(state);
	PlaneOpcodesLuaWrapper(state);
	TaskOpcodesLuaWrapper(state);
	CardDecksOpcodesLuaWrapper(state);
	DebuggerOpcodesLuaWrapper(state);
	DecisionMakerCharOpcodesLuaWrapper(state);
	SequenceOpcodesLuaWrapper(state);
	AttractorOpcodesLuaWrapper(state);
	GroupOpcodesLuaWrapper(state);
	ParticleOpcodesLuaWrapper(state);
	DecisionMakerOpcodesLuaWrapper(state);
	DecisionMakerGroupOpcodesLuaWrapper(state);
	SearchlightOpcodesLuaWrapper(state);
	CheckpointOpcodesLuaWrapper(state);
	TrainOpcodesLuaWrapper(state);
	ConversationOpcodesLuaWrapper(state);
	ShoppingOpcodesLuaWrapper(state);
	WeaponOpcodesLuaWrapper(state);
	CraneOpcodesLuaWrapper(state);
	TrailerOpcodesLuaWrapper(state);
	StreamedScriptOpcodesLuaWrapper(state);
	MenuOpcodesLuaWrapper(state);
	SkipOpcodesLuaWrapper(state);
	MenuGridOpcodesLuaWrapper(state);
	OtherOpcodesLuaWrapper(state);
	User3DMarkerOpcodesLuaWrapper(state);
	MouseOpcodesLuaWrapper(state);
	MemoryOpcodesLuaWrapper(state);
	FsOpcodesLuaWrapper(state);
	FileOpcodesLuaWrapper(state);
	DynamicLibraryOpcodesLuaWrapper(state);
	AudioStreamOpcodesLuaWrapper(state);
	AudioStream3DOpcodesLuaWrapper(state);
	FindFileOpcodesLuaWrapper(state);
	EntityOpcodesLuaWrapper(state);
	CleoBlipOpcodesLuaWrapper(state);
	ColPointOpcodesLuaWrapper(state);
	ClipboardOpcodesLuaWrapper(state);
	ImGuiOpcodesLuaWrapper(state);
	IniFileOpcodesLuaWrapper(state);
}