c_all = "Все модели объектов"
c_alpha_channels_and_non_collidable = "Прозрачные и без колизий"
c_nighttime_objects = "Видимые только ночью"
c_beach_and_sea = "Берег и море"
c_buildings = "Здания"
c_factories_and_warehouses = "Фабрики и склады"
c_stores_and_shops = "Магазины"
c_graveyard = "Кладбище"
c_houses_and_apartments = "Дома и квартиры"
c_offices_and_skyscrapers = "Офисы и высокоэтажки"
c_other_buildings = "Другие здания"
c_restaurants_and_hotels = "Рестораны и отели"
c_sports_and_stadium_objects = "Спортивные заведения и стадионы"
c_bars_clubs_and_casinos = "Бары, клубы и казино"
c_car_parts = "Части машин"
c_weapon_models = "Модели оружия"
c_industrial = "Индустриальные"
c_general_industrial = "Общее"
c_construction_industrial = "Строения"
c_cranes = "Краны"
c_crates_drums_and_racks = "Ящики, цистерны и стеллажи"
c_interior_objects = "Объекты интерьера"
c_bar_items = "Предметы из баров"
c_shop_items = "Предметы из магазинов"
c_household_items = "Предметы домашнего хозяйства"
c_furniture = "Мебель"
c_doors_and_windows = "Двери и окна"
c_clothes = "Одежда"
c_tables_and_chairs = "Столы и стулья"
c_casino_items = "Предметы из казино"
c_more_interiors = "Больше интерьеров"
c_land_masses = "Ландшафт"
c_concrete_and_rock = "Бетон и камень"
c_grass_and_dirt = "Трава, земля и грязь"
c_miscellaneous = "Разное"
c_street_and_road_items = "Дорожные и уличные объекты"
c_food_and_drinks = "Еда и напитки"
c_special = "Специальное"
c_military = "Военное"
c_pickups_and_icons = "Пикапы и значки"
c_ladders_stairs_and_scaffolding = "Лестницы, ступеньки и леса"
c_trash = "Мусор"
c_lights = "Освещение"
c_map_markers = "Маркеры для карты"
c_nature = "Природа"
c_rocks = "Камни"
c_trees = "Деревья"
c_plants = "Растения"
c_structures = "Сооружения"
c_airport_and_aircraft_objects = "Аэропорты и авиация"
c_car_parks = "Паркинги, стоянки"
c_farm_objects = "Предметы из ферм"
c_fences_walls_gates_and_barriers = "Заборы, стены, ворота и барьеры"
c_garages_and_petrol_stations = "Гаражи и заправки"
c_ramps = "Трамплины"
c_signs_billboards_and_statues = "Знаки, вывески, биг-борды и статуи"
c_transportation = "Транспорт"
c_railroads = "Железные дороги"
c_roads_bridges_and_tunnels = "Дороги, мосты и туннели"
c_wires_and_cables = "Провода и кабели"
c_construction = "Сооружения и детали конструкций"
c_stunt_tubes = "Трубы и конструкции для стант-гонок"
c_walls = "Стены"
c_modular_island = "Части островов"
c_samp_particles = "Частицы (партиклы) из SA-MP"
