[cpp]
enum_item_runtime = "{{ \"{}\", {} }}"
enum_item = "\"{}\", {}"
enum_declaration_runtime = """
state.new_enum<{}>(\"{}\", {{
        {}
    }});
"""
enum_declaration = """
state.new_enum(\"{}\",
        {}
    );
"""
enum_file = """
#include <sol.hpp>
#include <cimgui.h>
void {}(sol::state &state) {{
    {}
}}
"""
enums_file_bind = """
#include <sol.hpp>
{}

void bindEnums(sol::state& state) {{
    {}
}}
"""
enum_bind = "bind{}(state);"

[teal]
enum_record = """
global record {}
    {}
end
"""
enum_record_item_digit = "[\"{}\"]: integer"
enum_record_item = "{}: integer"

[lua]
enum_record = """
---@enum {}
{} = {{
    {}
}}
"""
enum_record_item_digit = "[\"{}\"] = {}"
enum_record_item = "{} = {}"
