[nodes.node_editor]
title = "Node Editor"
incorrect_pin_kind = "x Same input/output contacts"
incorrect_pin_type = "x Incompatible contact types"
create_link = "+ Create link"
create_node = "+ Create node"
node_context_menu = "Node context menu"
pin_context_menu = "Pin context menu"
link_context_menu = "Link context menu"
delete = "Delete"
type = "Type: %s"
contexts = "Contexts"
variables = "Variables"
variable = "Variable"
rename = "Rename"
edit = "Edit"
player_position = "Player position"
clear_anim = "Clear animation"

[nodes.node_editor.details]
title = "Details"
name = "Name"
type = "Type"
default_value = "Default value"
value = "Value"

[nodes.node_editor.categories]
main = "Main"
debug = "Debug"
project = "Project"
scene = "Scene"
actor = "Actor"
audio = "Audio"
checkpoint = "Checkpoint"
object = "Object"
particle = "Particle"
pickup = "Pickup"
pyrotechnics = "Pyrotechnics"
train = "Train"
vehicle = "Vehicle"
visual_effect = "Visual effect"
player = "Player"
variable = "Variable"
global_variable = "Global variable"
objective = "Objective"
char = "Character"
[nodes.types.core]
flow = "Flow"
number = "Number"
bool = "Boolean"
string = "String"
Char = "Ped"
Object = "Object"
Checkpoint = "Checkpoint"
DecisionMakerChar = "DecisionMakerChar"
Searchlight = "Searchlight"
AudioStream3D = "AudioStream3D"
AudioStream = "AudioStream"
Vehicle = "Vehicle"
ScriptFire = "ScriptFire"
Particle = "Particle"
Train = "Train"
[nodes.core.on_start_project]
title = "On project start"

[nodes.core.debug_print]
title = "Debug print"

[nodes.core.on_start_scene]
title = "On scene start"

[nodes.core.main_loop]
title = "Main loop"

[nodes.core.branch]
title = "Branch"

[nodes.core.comprasion]
title = "Comparison"

[nodes.core.invert]
title = "Invert"

[nodes.core.wait]
title = "Wait"

[nodes.core.spawn_actor]
title = "Spawn actor"

[nodes.core.destroy_actor]
title = "Destroy actor"

[nodes.core.get_char]
title = "Get character"

[nodes.core.play_audio]
title = "Play audio"

[nodes.core.stop_audio]
title = "Stop audio"

[nodes.core.spawn_checkpoint]
title = "Spawn checkpoint"

[nodes.core.destroy_checkpoint]
title = "Destroy checkpoint"

[nodes.core.spawn_object]
title = "Spawn object"

[nodes.core.destroy_object]
title = "Destroy object"

[nodes.core.get_object]
title = "Get object"

[nodes.core.spawn_particle]
title = "Spawn particle"

[nodes.core.destroy_particle]
title = "Destroy particle"

[nodes.core.spawn_pickup]
title = "Spawn pickup"

[nodes.core.destroy_pickup]
title = "Destroy pickup"

[nodes.core.spawn_pyrotechnics]
title = "Spawn pyrotechnics"

[nodes.core.destroy_pyrotechnics]
title = "Destroy pyrotechnics"

[nodes.core.spawn_train]
title = "Spawn train"

[nodes.core.destroy_train]
title = "Destroy train"

[nodes.core.get_train]
title = "Get train"

[nodes.core.spawn_vehicle]
title = "Spawn vehicle"

[nodes.core.destroy_vehicle]
title = "Destroy vehicle"

[nodes.core.get_vehicle]
title = "Get vehicle"

[nodes.core.spawn_visual_effect]
title = "Spawn visual effect"

[nodes.core.destroy_visual_effect]
title = "Destroy visual effect"

[nodes.core.set_variable]
title = "Set variable"

[nodes.core.get_variable]
title = "Get variable"

[nodes.core.number_to_string]
title = "Number to string"

[nodes.core.calc_number]
title = "Calculator"

[nodes.core.concat_string]
title = "Concatenate strings"

[nodes.core.set_global_variable]
title = "Set global variable"

[nodes.core.get_global_variable]
title = "Get global variable"

[nodes.core.emit_signal]
title = "Emit signal"

[nodes.core.is_current_objective]
title = "Check current objective"

[nodes.core.on_start_objective]
title = "On objective start"

[nodes.core.while_for]
title = "Repeat until"
to = "Until"
on_true = "On true"

[nodes.core.char_follow_path]
title = "Follow path"
on_complete = "On completion"
start_from_nearest = "Start from nearest"

[nodes.core.char_animation]
title = "Animation"
on_complete = "On completion"
play_type = "Play type"
play_types_info = "Normal - plays the animation\nUninterrupted - plays an animation that cannot be interrupted\nSecondary - plays upper body animations\nSpecial - plays animation with additional parameters"
unlock_x = "Unlock X"
unlock_y = "Unlock Y"
lock_f = "Lock last frame"
disable_force = "Disable interrupting"
disable_lock_z = "Unlock Z"
play_types = ["Normal", "Uninterrupted", "Secondary", "Special"]

[nodes.core.boolean_operations]
title = "Logical Operations"

[nodes.core.get_checkpoint_data]
title = "Get Checkpoint Data"

[nodes.core.merge_flow]
title = "Merge Flows"

[nodes.core.cutscene]
title = "Cutscene"
point_to_x = "Camera Point X"
point_to_y = "Camera Point Y"
point_to_z = "Camera Point Z"
on_complete = "On Complete"
entities_types = ["None", "Actor", "Vehicle", "Player"]

[nodes.core.follow_carrec_path_vehicle]
title = "Start Carrec Path for Vehicle"
on_complete = "On Completion"

[nodes.core.stop_carrec_path_vehicle]
title = "Stop Carrec Path for Vehicle"
